name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

permissions:
  contents: read

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 20.x
        uses: actions/setup-node@v4.1.0
        with:
          node-version-file: .nvmrc

      - name: clean install
        run: npm ci

      - name: check format
        run: npm run format:ci

      - name: check tests
        run: npm run test:ci

      - name: publish
        run: npm run publish

      - uses: actions/upload-artifact@v4
        with:
          name: "distribution"
          path: "*"
          overwrite: "true"
  test:
    runs-on: ubuntu-24.04
    needs: build
    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      NOTION_ROOT_PAGE_ID: ${{ secrets.NOTION_ROOT_PAGE_ID }}
    steps:
      - name: download
        uses: actions/download-artifact@v4
        with:
          name: "distribution"
      - name: check integration test
        run: npm start
  release-please:
    needs: [build, test]
    if: contains(github.ref, 'heads/main')
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-24.04
    steps:
      - name: download
        uses: actions/download-artifact@v4
        with:
          name: "distribution"
      - uses: googleapis/release-please-action@v4
        with:
          release-type: node
