name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

permissions:
  contents: read

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-24.04
    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      NOTION_ROOT_PAGE_ID: ${{ secrets.NOTION_ROOT_PAGE_ID }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
          fetch-tags: "true"

      - name: save version
        id: bump
        uses: licenseware/bump-version@v1.2.87

      - name: save version
        run: |
          echo "GHA_VERSION=${{ steps.bump.outputs.version }}" >> $GITHUB_ENV

      - name: Set Node.js 20.x
        uses: actions/setup-node@v4.1.0
        with:
          node-version-file: .nvmrc

      - name: clean install
        run: npm ci

      - name: check format
        run: npm run format:ci

      - name: check tests
        run: npm run test:ci

      - name: check integration test
        run: npm start

      - name: publish
        run: npm run publish

      - uses: actions/upload-artifact@v4
        if: contains(github.ref, 'origin/main' )
        with:
          name: "distribution"
          path: "*"
          overwrite: "true"
  test:
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - name: download
        uses: actions/download-artifact@v4
        with:
          name: "distribution"
      - name: check integration test
        run: npm start

  publish:
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - name: Get the new version
        run: echo "The new version is ${{ env.GHA_VERSION }}"
